### PR TITLE
Logging

### LINKED ISSUE #4: Add a way for developers to add logging handlers
Assertions are great in development, but they are typically compiled out in production. RZAssert should provide a way for developers to add logging/analytics methods that get fired off before the assertion is thrown.

### LINKED ISSUE #9: need parentheses around tests
Consider `RZASSERT_FALSE`:

```objc
#define RZASSERT_FALSE(test) \
    NSAssert(!test, @"**** Unexpected Assertion **** \nSelf: \"%@\"", self)
```

`test` is not parenthesized, so if you pass in an expression such as `foo != bar`, only the first part will be negated (`!foo != bar`), which may not produce the result you were expecting. It should be `!(test)`. There are probably other cases like this as well, but this is the one I noticed.

### LINKED ISSUE #13: Need do {} while (0) around multiline statements
for these reasons: http://stackoverflow.com/questions/1067226/c-multi-line-macro-do-while0-vs-scope-block

### LINKED ISSUE #14: Remove bare RZASSERT → NSAssert define
This should be removed:

```objc
#define RZASSERT NSAssert
```
I've seen this line confuse people, thinking it will do the same thing as the other macros. And with the logging planned in #4, a developer who accidentally uses `RZASSERT` by itself will be missing out on useful logging.

### PR DESCRIPTION
**Pull request by ZevEisenberg**
You may want to view this by commit, rather than in total, because of CocoaPods diffs. Alternatively, just merge #17 first, since it takes care of all the messy project changes.

Fixes #4 
Fixes #9 
Fixes #13 
Fixes #14

### CODE REVIEW

**Comment by ZevEisenberg** [comment]
Ah, I think I can do the build thing in the Rakefile. I should be able to run the tests twice, once with `NS_BLOCK_ASSERTIONS` defined, and once without.

**Comment by ZevEisenberg** [comment]
@mgorbach this is nearing readiness. Question: have a look at `RZAssert.h.` It's getting pretty messy, with a lot of repetition, and it's pretty unreadable. It also has one method (`+logMessageWithFormat:`) that shouldn't be public, and is only here because the macros need to use it. Since the `RZASSERT_*` macros are now supposed to run all the time, not just in debug builds, what would you say to the idea of changing them all to functions, and hiding all the macro ugliness in the .m file?

**Comment by mgorbach** [comment]
You should really try to clean up the repetition here since it's asking for bugs and pain in the future. Ideally you would find a way to run the preprocessor more than once so you can double-expand (`#if` inside `#define`). If that doesn't work, at the very least, you can check the assertion condition and generate the error / message string only once, and then use the while pattern to use it in two different ways, depending on the assertions enabled state. To make things even clearer, you can even do something like `#define LOG_ASSERTS !NS_ASSERTIONS_ENABLED` so you don't keep re-typing that.

**Comment by mgorbach** [comment]
Many of your `RZCAssert` log statements appear to include `self`. That is a no-on and will cause painful problems with retain cycles.

**Comment by mgorbach** [comment]
This file is getting big (`RZAssert.h`). It might be a nice idea to pull it apart into logging components, shared components, and the actual assertions.

**Comment by mgorbach** [comment]
Check out `NSException.h` itself. It has recursive macros!

**Comment by mgorbach** [comment]
`NSBlockAssertion` is a mix of the implementations of `NSCAssert` and `NSAssert`. It formats the result like an assertion in an Objective C method, but does not capture `self.` `NSCAssert` also avoids capturing self, but it formats results as if you were in a C function (__PRETTY_FUNCTION__ instead of _cmd).

**Comment by ZevEisenberg** [comment]
@mgorbach this is ready to go (again). I did think of one possible final way to shorten the file:

```objc
#define RZASSERT_WITH_MESSAGE_LOG(expression, message, ...) \
    do { \
        RZASSERT_BASE( NO, @"**** Unexpected Assertion **** %@ \nExpression: \"%@\" \nSelf: \"%@\"", [NSString stringWithFormat:message, ##__VA_ARGS__], expression, self ) \
    } while(0)
```

This could be shortened to:

```objc
#define RZASSERT_WITH_MESSAGE_LOG(expression, message, ...)  RZASSERT_BASE( NO, @"**** Unexpected Assertion **** %@ \nExpression: \"%@\" \nSelf: \"%@\"", [NSString stringWithFormat:message, ##__VA_ARGS__], expression, self )
```

But it seemed like there would still be ways that that could break things if it’s not enclosed in a do/while.

**Comment by mgorbach** [comment]
This looks good, @ZevEisenberg. Just make the tweak to fully no-op assertions when logging is not activated and assertions are disabled, and you are clear to commit and release.

**Comment by ZevEisenberg** [comment]
@mgorbach this is ready. Travis seems to have given up for some reason, but you can run `rake test` yourself to see that tests are still working.

**Pull request merged**
