### PR TITLE
Feature/jstricker/documentation of with message

### PR DESCRIPTION
**Pull request by jatraiz**
@ZevEisenberg @mattThousand here's a small documentation update highlighting the custom message macros

### CODE REVIEW

**Comment by ZevEisenberg** [comment]
@jatraiz I wouldn't say that "most" of the RZAssert macros have a "with message" variant. Only the ones that assert always or assert true.

**Comment by ZevEisenberg** [comment]
@jatraiz also, your change to the markdown file… somehow failed the build? No idea what's going on. Probably unrelated.

**Comment by jatraiz** [comment]
@ZevEisenberg ok edits made

**Comment by ZevEisenberg** [comment]
@jatraiz #finally

**Pull request merged**
